language: node_js
node_js:
- '10'
script:
- npm run build
deploy:
  provider: npm
  on:
    tags: true
    repo: joernb/react-redux-substate-provider
  email:
    secure: P0YLS50aSYrNOacu8kHtWhWif4r1xRdcsZFvhy3b47UXeWezWhL1M5CsP1tChSt4X536u6TvQ5mLsIFnRQ39WgSe0zjpw+BBDCrQIpRXQP5LPwaDygzWoqxTomDXX2LDgHOMzCgSe+mUt69UWq8C4RyIMNwwKypO4itaa0KDHrhmaanFG2bnc8lCC2YDWmH7dHQsn2lr8oomJKov0adxptSx0YjDRkv6kO/NrA2Tu2ESb/7UHbUG/sUVYcaAKzYDoT0a5yKdbWaw13/JBoaUA2kOyXvn+H8R/vJs2oFpn+jo1UWNAa3Le++LDeifv8ag4rX0wW4mJt2dDigpkIaaXFV6UxpSb5z+mhLP/ZOJ/W+n18iDObkcqG+MDPfEMVQpKIt8TAxJI3Hjjzn+EJVahJpg4pcQ8/tpqK4El1F3YyxP+r5x/OcRmNGF7Z5S2hpmZBLuUBnxEiytuSCUkfgTqc88HGJpuBPKUg0gOGfgCjJZIy6TwNKcE1UC9zPoNrJlCYbu+qDez3O5Ca0v8Xeu6lYtUUzRpWMYd7Klx4hY/3Arb1e3UwNCzvv7UA/DIEjv/Hl3TrHRZ8Uo/j2H/RpZuv22ap/SsmcJuZQDuDfTsJ5G8SJv55BUeYWp42srv4dJHyghiiP7l6Y4iB24JS6CACMU/Kl1M0xFvd5NpJXTpdE=
  api_key:
    secure: s4B54Su708I7sk7/mz6rcR1ik7JjymdEZXWqOnO/t2oPuPG6KQliIZOtj7FbfTeOf3l0EASC4AFpSiS7Y/bquwioNgC3tpc3MJnZYws4Pzk15+RQsod+mk5fR8MVbigCz3/wdKIKz8shYPtrUuGhxhKBqqJXlyH175aYU1xaZ6g4kRtFegijBAY5WTeAUE1C2Il/O8c/q6O30HtP2s8xm4/9GTPLho0nLlNYa2DsE7Tq2tyX6JD9WH+m2OYGfaegDqv/Cdn/ziY/uK1FhGAWYDsutPi0kY1ND78keL2jyABa8+VKR3Q58P2F2b59UuZixofsu4A/bUOWfiuidpt+MYk7OsdJD91SpudhtJMDMWDdAT3KJr8YplYm8i18nKJBzALM3V+yvXrnNLx3NIVCjYVAN6Yj8KtmXE1PK8TNqFXdnZgaTUwoXtcHPJ7hV/a7y1Rqi1wkYQ6jgi5DZKtUWtMpwD3EaW927EJkXOkWYoaZFIuJyZel0po3+PMxLm/srik9VNME6t+JaU32ijgOhPhCgAe03s/VZJnmbQYjlf6klHAqlNdtHQa0aY9+jv/+65qFciswhat2Zlvl+f+0Sb7EeUeTHxnHK6HQVlhWnZKUyvPLF7XRTV/jkXP+NheqhRdS6hPAyGYF2fV0aAG5uAV6+VIjPv1HQPuq8jhXkuw=
