language: node_js
node_js:
- '10'
script:
- npm run build
deploy:
  provider: npm
  on:
    tags: true
    repo: joernb/react-redux-substate-provider
  email:
    secure: cRbU1U+X57HVsvpwRh563F2JkMlJWg5ZFZu1qH7K6KyDVeNjL2TDDwaik2GudM6ZOB6b29dwGvFey1AJTG1jwGdfgasJXwQj26uJiTr4eaXIR1GiPAKnzBgk2na+2GraS65xfgqB5RIF89pbPe/y9zevs37Xo97J9D8PRfMRPAFLpHDutki0ElGb1QGbnlIsOUEQ1gm0/OnMgtMr6QgCwYsOZEHt/9JgDxscYpwfW3U8U8VueMTfh12XtVA1mg54HuMc0aLOmVOHi84fqFP1aU4FSh7zgzIoFUE8MOZQMU6bHD6OEUd4q+udK57XMUUDODCgoPy3BJHkRBASrdrqFnstLbd5FcRPTojWdf4byk7iPEU8Hczp2V9SIR4N4nFFIjWc3qIWRLkvR0B2/SbNR+vH29r4Dkf6kXR6HGifzwDexlGbIWd9xmMgo7npJXL7o12ghf/xXsv9hNuVtBOQ26JSD+cAYaYbcQ1uEL+j6GVebKff3vUZfkO8swu3JrmeidO101agGX+66mfxsUKPxpcM2mn7lPKfohaNYvzsZxm5LyBhkZ7H/VDgEkHImlwi4lfWHgcqY9etdM7we0ezI2KkgrLsliVOBw8jtesKgyTcboGYuaMuNWcug3UVUldpXYnpR862mD6QHMvgFxD9v7u3RKVBUBGbpEZ7/54W22o=
  api_key:
    secure: JOhsTbKppPIqCryQ5VR4SpGJEdFQ9nYgj5Wl7vjW0EI2rf0NhcVNQbGVmIOHmyjhwP1vCNAOjJ9ocazKQQZXZvYlI2EyguIP46FabhEzf3cYeHjtloXoTTqyBK7lZf3vEhjW2ozCHK9+fAGevLloJulA1xxMu7405UVa6bNnmjmhNGdD5Ir9+OfGmyctgbqZFhNPdnzkYfoLGcVWaPT3noB5OUAUrfTHg8EbiwrPjJoiCGTqUwmVxiFZONjPL4gTFYGZzSB/98uD/z6RM1vzI9EEjaBLlv1nNviFZa2M/R3jvag9G1do9K1fTzUFH0NwUOCn2w6jknQJKJN1bQJQdfcBt2BC8fIcENbIQtXGh+8yqUOVwTzCjfNWT071tEEa3J8eGt+59zvz9zo0BHufGKGc/lt6+/Ui3TA06pfEpNH/vmGTLPnOXwLNkdTOO4+XnZzV/z/+U4L5qp4gMnWUSjvXGT2vLbwOudH829/PWqqOx605GufI0rDvkseEB8EfhAvuUyl7K3Yq2P9UpW5qt6N2k1+8ZrFT0DyJTDwTNC8CDBDdmqyO9zm4fF+msWfR4a4bX4xvgrTUzkpN7b2J8cACdmJWrW7CwO72LtZ6oSeTXr3sy53ENWjZ+fzLdlgfFtb1tbaFMoONq/8eIlVdxYBDbHnxKkwNNTAvR6QoD7U=
