language: node_js
node_js:
  - "10"
script:
  - npm run build
deploy:
  provider: npm
  on:
    tags: true
    repo: joernb/react-redux-substate-provider
  email:
    secure: AaN9r84PpYL846gn4Fmmg3lluTqKmhhLiSj9uemHdXt5nB2qJJCTL0eVIp2VIXK3UKNKxKkzGVZ7EAZ9uagWxT8j9jyGGfO+Od7rDCDmuoYAHtKav2DrU5ujxGBC5XLUuor9Z455A3iF16Yivz2GWNo8RdpJ9wIaIqFUvDrusXC4Tz1X/EGfpBPlwNOIYXaE9QoVB19q4I/3FqnMmrSsnoKfD71LsHxrEyUPV0atKkbrrgL3o28fWvYBQNw5j2DWDvQHWEgd9TDV08ozzK54VW+2HJDLbeQttzvwOHoz8PPYJHKLkG6I1Ik35rUTVjDdPYAn85kTGhnefe9aF+H1gI6WOX0ePPc6HR8QBuPqiSYNpPN5kG2LMME9LzXFVY8qv1aVgZpQZU7psJh2LKFyn1LzmmOn32kx91l0YNMNGl6u8vdfQAgeKheHUm2/yQ7D2Kt7wXeIEjXhkMMPSPHPqZbD9L3lSINmqqx8Rw1JXLgH/YrlMaaG8OAd7GKQBEsZrvBJjjOaPcdIf5iTSzNgRPf/8hgVRRupjzmLP4C4w7o83MP3WAhPa0riCBoeWUV7a2BcK8dH0qrsiTfoFN5CmzT8L4hsB30nqZ76bSu5tutqAJ5rqi9g9yD63q+GKe3wdK58mRHrRxxwmBnJEpefWhSO2fuNGPuGdViTgOcugqM=
  api_key:
    secure: UTC/F99AgC024ImVhSavHw5W5c60dSU8ks4J5twi4nb2N5D6/YlnmNWuhHFWR/yivoQtwnadXvRvUy0dQnUzdsnbkjwQribOOr3orNSdMDRamql2X52WHKs1Yz4VNwimr3xdoV8G4PJvzE4HtKAkJoEEyz3YQ++iwZPtBwhI/gYAlxvApy4QN9W7RhWZpki8OsknVajN5w5AuURn/wvucwaoTOzy15gSkRi+a3kmJ/O9Gw+chFVQGNDAGgP7v+CTaTMhyU5nsjL43hlfCMH2RultUwz7LodIaKFD2cyt1sMRzljBVjjJ1ZDf5EHkAStHbVLnauXPfh7RJyX15cRzir5XVUTgDM2tkmgM/S5oGJ9U+SEdW6oRg86ybY4suBKoPJOrlmpErHvsT76IkWWZ1v+StfE3OLJOyNvci4r7MOA11NILL2Rb15Q9LHLKSJSEghx0W+Lq2cl0/ysqCP/1eds8yGJbZPwPdO5TbuuzLdzKK7J+krAXsvU50usvbUWFgOoi6M+Ija86aEGAQJ2O+kX0H9E5B/IsqGzcjoWk1bvP81QLljGA1DQ4dO95XSLlrQneF/0ZfyjgdqD68apZm3gECjgGF/5MVqibF0fPlCZFVDdmqu4GJP36/fpsQlPw162qHFXvR8/Tound/b3hAmm3kAAuHb5qhMsomI7HpaY=
